### ISSUE TITLE
Feature request: transfer all sessions in one go

### ISSUE THREAD

**Issue by guidomeijer** [int-brain-lab/iblenv#10]
Currently when you launch the transfer for the video or ephys it asks whether the path is correct for each session. This is not handy if you want to launch the transfer of a bunch of sessions because the query pops up after each session and you have to be at the computer to provide input. It would be better if it asks whether the path is correct or needs to be changed for all sessions first and then starts the transfer of all sessions in one go.

**Comment by nbonacchi** [comment]
If you're sure all the sessions will go to the default destination folder, i.e. mouse/date/001 (meaning you ran the behavior only once and the prepare_video/ephys_session only once and everything went OK) the command prompt actually has a memory of the commands you send it while it's busy doing something else, so pressing enter multiple times will respond (y)es to all the prompts before it starts copying. Not optimal I know, ideally you'd like a memory of the responses and possible changes and then start the transfer.

**Comment by anne-urai** [comment]
Related: https://github.com/int-brain-lab/iblscripts/issues/25

**Comment by anne-urai** [comment]
A hack to transfer multiple recordings in parallel overnight (so you can clean the disk the next morning):

For each recording (one by one), create the `transfer_me.flag`, start the transfer script in a new anaconda prompt window, then rename to `transfer_me_tmp.flag` or something else. Once each copy is running in its own window, rename all the flag files back to their original. This will copy each of them much more slowly (since they will run in parallel), but will at least allow you to transfer all data overnight.

**Comment by micheleangelofabbri** [comment]
Feature has been implemented.
