### ISSUE TITLE
[Usage question] - How to retrieve via ONE sessions which have (any) brain regions associated to clusters?

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#101]
**Describe the question you have**
Posting a question on behalf of @yanliangshi  :

How to retrieve via ONE sessions which have (any) brain regions associated to clusters?

Those variables seem to be the ones to search on:
```
- clusters.brainLocationIds_ccf_2017
- clusters.brainLocationAcronyms_ccf_2017
- clusters.mlapdvIntended
- clusters.brainLocationIntended_AllenV2acronyms
```

However this query:
`ses = one.alyx.rest('sessions', 'list', django='data_dataset_session_related__dataset_type__name__icontains,clusters.brainLocationIds_ccf_2017')`
returns 25 sessions as output.
Is this query wrong ?

Should Yanliang be looking into channels instead?
https://github.com/int-brain-lab/iblenv/issues/21#issuecomment-683899946

**Is your question related to a specific product?**
ONE

**Additional context**
@yanliangshi please elaborate your question and write below your exact queries and output.

**Comment by yanliangshi** [comment]
Hello everyone,

I have tried to query the following ONE variables for the brain regions of channel or cluster:

'channels.mlapdv',
 'channels.brainLocationIds_ccf_2017',
 'clusters.mlapdv',
 'clusters.brainLocationIds_ccf_2017',
 'clusters.brainLocationAcronyms_ccf_2017',
 'channels.mlapdv',
 'channels.brainLocationIds_ccf_2017',
 'clusters.mlapdv',
 'clusters.brainLocationIds_ccf_2017',
 'clusters.brainLocationAcronyms_ccf_2017'

The query Gaelle mentioned only returns 25 sessions as output. Since there are more than 400 sessions with spikes data, I would like to know how to get access to the brain region label for the rest of the sessions. Thank you.
[num_1.pdf](https://github.com/int-brain-lab/iblenv/files/5510865/num_1.pdf)
[num_2.pdf](https://github.com/int-brain-lab/iblenv/files/5510866/num_2.pdf)

**Comment by mayofaulkner** [comment]
Hi, you can get the clusters from any dataset by using the brainbox function load_spike_sorting_with_channel. Example usage here https://int-brain-lab.github.io/iblenv/notebooks_external/docs_load_spike_sorting.html. This automatically gets the best estimate of the cluster locations.

**Comment by yanliangshi** [comment]
Hi Mayo,

sorry I have an issue, when I run the code:

spikes, clusters, channels = bbone.load_spike_sorting_with_channel(eid, one=one)
print(spikes.keys())
print(spikes['probe00'].keys()) 

I cannot get ''channels'' because of the following error:


---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-607-c91adb136382> in <module>
----> 1 spikes, clusters, channels = bbone.load_spike_sorting_with_channel(eid, one=one)
      2 print(spikes.keys())
      3 print(spikes['probe00'].keys())

~/Works/int-brain-lab/ibllib/brainbox/io/one.py in load_spike_sorting_with_channel(eid, one, dataset_types)
    224 
    225     # -- Get brain regions and assign to clusters
--> 226     channels = load_channel_locations(eid, one=one)
    227     dic_clus = merge_clusters_channels(dic_clus, channels, keys_to_add_extra=None)
    228 

~/Works/int-brain-lab/ibllib/brainbox/io/one.py in load_channel_locations(eid, one, probe)
     54         if len(i) == 0:
     55             continue
---> 56         trajs = ses['probe_insertion'][i[0]]['trajectory_estimate']
     57         if not trajs:
     58             continue

KeyError: 'trajectory_estimate'

**Comment by yanliangshi** [comment]
Btw, what is the difference between the best estimate of the cluster locations you mention here, and 'channels.brainLocationIds_ccf_2017'?

Can we use the 'best estimate of the cluster locations' of all sessions for the brain-wide activity map project? Or is there some QC and a subset of sessions we shall use?  Thank you

**Comment by mayofaulkner** [comment]
I think it looks like you are not using the latest code in ibllib. Could you try
```
cd ibllib
git checkout develop
git pull
```
and see if the code runs.

Best estimate means that if the final datasets (channels.brainLocationIds and cluster.brainLocationIds) are available it will download and use these locations but if these datasets are not yet available (for cases where the probe hasn't yet been aligned by > 2 people) then it will infer the channel locations from the histology traced track.

**Comment by yanliangshi** [comment]
It works, thank you for answering!

**Comment by mayofaulkner** [comment]
Great! I will close this issue but feel free to reopen if you need any further clarification!
