### ISSUE TITLE
[Feature request] - Change prompt 'session number' title in pyBpod GUI

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#113]
**Is your feature request related to a problem? Please describe.**
There was confusion with the prompt for the trial sequence in the GUI.

**Describe the solution you'd like**
Users request to 
- make the title more explicit (e.g. "trial sequence number")
- add a sentence such as "this should not be changed"
- for the number to loop from 1 to 12 and back to 1 automatically
- ideally, to make the prompt disappear altogether as it does not matter which sequence is used (as long as it is a different one than the day before ; even in the case of dud recordings)

**Comment by nbonacchi** [comment]
- _make the title more explicit (e.g. "trial sequence number")_
I'd propose: 
**Title of the window**:
"Confirm pregenerated session to load",
**Label of the prompt**:
"Load pregenerated session #"

- _add a sentence such as "this should not be changed"_
If it's not to be changed then it should not appear at all. Nonetheless, the prompt is essential in case something wrong happened with the previous session (i.e. crashed) and the session should be repeated. It's effectively an override of the automated progression.

- _for the number to loop from 1 to 12 and back to 1 automatically_
I don't see a reason for this, the requested number of sessions was 10 which was above the planned number od fessions per animal. Does this happen, mice that have more than 12 recording sessions? I never had to fix a bug where the session would not run because of this. 

- _ideally, to make the prompt disappear altogether as it does not matter which sequence is used (as long as it is a different one than the day before ; even in the case of dud recordings)_
This is the easiest thing to do but it should be approved by physiology WG and theory WG as the feature was implemented by their request. I'm not sure it does not matter; a possible consequence of this is not having enough comparable sessions across recordings where the stimulus sequence is exactly the same because of random skips of pre-generated sessions on different subjects.

**Comment by njmiska** [comment]
Regarding the title, I would suggest we do not use the word "session" at all.  Maybe "pregenerated trial sequence" would be more explicit and also less confusing?

Regarding adding some kind of warning/sentence- maybe something like "please refer to section x.x of IBL recording protocol before changing this value".  It needs to be more explicit that this is generally not intended to be changed.

Regarding looping back to 1 after 12, just because no one has recorded more than 12 sessions from a single mouse yet does not mean that this is not feasible.  Why not add this now to avoid giving someone else a headache later?

**Comment by nbonacchi** [comment]
**title**: pregenerated trial sequence "N" is also not really accurate as the 1st session that is loaded can be pregenerated trial sequence e.g. # 6 then # 10 then # 3, etc it depends on the order that was fixed for that subject.
This order is fixed on the first ephys session, so what I really need to know is the progress in this order, i.e. if I'm supposed to load the next experiment or the same as before bc something crashed. Additionally, when repeating sessions for multiple QC reasons, users will need to be able to say, I'm repeating e.g. the 3rd session for this subject, so the number is not a cardinal its actually an ordinal. I don't know the best way to convey this in a one liner...

**warning**: I'm against it, either we remove the prompt altogether or, users should have access to proper docs, and the wording should be clear. No one is going to go to the docs with a mouse in the rig and wanting to run an ephys session. Either   

**looping**: the issue with looping is not technical, its experimental, 12 sessions mean 24 probe insertions, I believe we decided that 18-20 would already be on the high side in terms of brain viability. @GaelleChapuis probably knows best the recording procedure limit for each subject. I don't think we should ever reach 12 ephys double insertion sessions with the same subject. Future headache avoidance has to be counterbalanced with premature optimization of something that will never be used.

**Comment by nbonacchi** [comment]
**title**: what about "Load trial sequence for recording day number:" ?

**Comment by GaelleChapuis** [comment]
From what I understand, there is a regenerated set of trial sequence (#1-2-3-...-12).

For each subject, the order of such set is randomized, e.g.
For subject A it would be :  # 3 - 5 - 2 - 1  - 12 - 7 - etc
For subject B it would be:   # 7 - 9 - 6 - 5 - 10 - 8 - etc

This number is what needs to be input in the prompt.

Given this randomness, I think it would be OK to remove the prompt altogether, and loop over number. Explanation below:
Let's assume that for subject A, the 3rd session was a dud.
The recordings would thus happen in sequence: # 3 - 5 - 1 - 12 - 7 - etc.  which seems perfectly acceptable.

Now let's assume a lot of duds happens (5 times) :
 # 3 - 5 - 2 - 1 - dud for 5 sessions - 10 - 9 - 6
In this case, 7 real sessions were recorded. 
If an 8th session were to be recorded following this, ideally the sequence chosen would be within the missing ones (4, 7, 8, 11, 12). However, my understanding is that we cannot know which session is a dud from pyBpod. I do not think the user will remember which sequence number to use either (@njmiska point of view welcome here).

Thus, I would suggest that when j=12 is reached (j being the number of sequence set used ; in this example, when j=12, #sequence=6), a new sequence is drawn (e.g. 6 - 10 - 2 etc) as would be for a new subject. And this sequence is used going forward.

This would not guarantee that each mice see the exact same set of trials, but it's probably the easiest on the user.
Thoughts welcome !

**Comment by nbonacchi** [comment]
> This number is what needs to be input in the prompt.

@GaelleChapuis no, the number that is inputted in the prompt is the session number (hence the name) 3 for the 3rd session, 4 for the 4th, etc... This is independent of the order that was drawn. So if the 3rd recording is a dud, the next day/session the prompt will ask if it's OK to load session 4 and the user can say, no load session number 3 because yesterday/previous session was wonky... the order of the sessions is drawn and saved in the settings file but the user does not see the actual number/ID of the pregenerated session.

**Comment by GaelleChapuis** [comment]
OK I see, the prompt displays the index "j" as per my example above.

**Comment by njmiska** [comment]
yes I agree, this title clears up most of the issue.

I still don't understand why not loop past 12 however?  There is nothing inherently preventing someone from recording 12+ days from a mouse, the only limitation is damage/infection (which can both be avoided).  Would this be difficult to implement?

**Comment by nbonacchi** [comment]
Not at all, difficult to implement, I just have to reset the counter automatically. It still would work manually as is as long as when the user sees the number 13 in the prompt they manually reset it to 1. 

The quality of the recordings is the major impediment. The fact that we already have hundreds of penetrations and this has not been an issue should serve as an indicator that 12 sessions for a single mouse is well above what people record. I believe weŕe stopping at 6,7 recording sessions i.e. 12-14 probe insertions.

The text is already changed and committed to develop, will come out with next release or bugfix.

**Comment by njmiska** [comment]
Ok, great, thanks.  I just see this as something that doesn't really have a downside, and if it's easy to implement, then why not?  It's not like we're encouraging people to continue recording if quality becomes bad.  If we decide not to implement this, then we just need to make sure that it is very clear in the documentation that if a user chooses to go past 12 sessions, they will need to manually reset this to 1.

**Comment by nbonacchi** [comment]
Closing this, feature implemented and will come out w next release of rig

**Comment by GaelleChapuis** [comment]
So just to confirm:
- could you send me a screenshot of the new prompt
- what feature is implemented, going from 12 to 1 automatically?
