### ISSUE TITLE
[Bug report] - No extended qc field for some insertions

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#123]
**Describe the bug**
Looking at the repeated site data, there seem to be insertions without the extended qc:

no extended qc NYU-26, 2020-08-18, probe00
no extended qc NYU-29, 2020-09-21, probe00
no extended qc NYU-30, 2020-10-19, probe00
no extended qc ZFM-01577, 2020-10-27, probe00

There seem to be more (117) according to this query:
```
ins = one.alyx.rest('insertions', 'list',
django='session__project__name__icontains,ibl_neuropixel_brainwide_01,'
'session__qc__lt,50,'
 'session__extended_qc__isnull,True')
```

**Comment by mayofaulkner** [comment]
For probe insertions prior to release of ibllib 1.5.20 the qc and extended qc fields were not added to json field when probe insertion was created. As soon as tracing is conducted these fields are added to the probe insertion json so that the results of qc can be monitored. 

The generic query to search for such cases is 
```
ins_without_qc_field = one.alyx.rest('insertions', 'list', django='json__extended_qc__isnull,True')
```

For now I have patched these probe insertions using this code https://github.com/int-brain-lab/ibldevtools/blob/master/Mayo/2020-12-02_add_qcfield_to_insertions.py
