### ISSUE TITLE
[Bug report] - stimFreeze extraction innacurate

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#127]
**Describe the bug**
stimFreeze is not extracted properly. Algorithm needs changing, data looks fine.

**To Reproduce**
Example mock session:
eid = 13bd02ba-d8ba-4da0-97ec-fba997ddc9ab , trial 19
<img width="902" alt="Capture d’écran 2020-12-04 à 17 48 37" src="https://user-images.githubusercontent.com/43007596/101190863-43a7ed00-3659-11eb-9425-c2d58b263abb.png">

stimFreeze not present on that trial, but the TTL signal looks fine.

**Comment by k1o0** [comment]
This may have been solved with @oliche's new ephys extractor.  I'll assign to him for now.

**Comment by GaelleChapuis** [comment]
session '193fe7a8-4eb5-4f3e-815a-0c45864ddd77', several trials have `response_stimFreeze_delays` negative due to stimFreeze extraction error.
Example trial 616 (value: -1.55)
<img width="1015" alt="Capture d’écran 2021-01-25 à 14 07 23" src="https://user-images.githubusercontent.com/43007596/105710747-d0fc1500-5f17-11eb-803a-1a9b0bbf72de.png">
Example trial 158 (value: -0.64)
<img width="951" alt="Capture d’écran 2021-01-25 à 14 17 12" src="https://user-images.githubusercontent.com/43007596/105710976-2b957100-5f18-11eb-82a2-c0d02cda7042.png">

It appears from these trials that stimFreeze (that is a command) cannot be accurately represented in the TTL trace, and thus should not be extracted. @k1o0 thoughts on this ?

**Comment by nbonacchi** [comment]
stimFreeze is the moment the stimulus freezes i.e. the one before last frame2ttl polarity switch of the trial.
the command is stimFreezeTrigger, all *Trigger_times are the commands as seen by bpod (which requires alignment to the FPGA clock).
I don't think either stimFreeze datasets are extracted by either pipeline, they are just calculated for the QC.

**Comment by GaelleChapuis** [comment]
Note: I cannot look at the trials TTLs using `ipython task_qc.py 13bd02ba-d8ba-4da0-97ec-fba997ddc9ab` as there is `No extractor for task mock_ephys`. @nbonacchi we should revisit this choice eventually (or at least discuss definitions), as MOCK is not the same as TEST (mock is a real session with real data, that needs extraction; for the moment we are asking experimentalists not to do MOCK sessions due to the delay variable extraction). This is not urgent.

As for the stimFreeze, should we use the Trigger_times in the QC rather than trying to measure it from the frame2TTL (as it may not be detectable accurately, the TTL pulse remaining in the same state) @k1o0  ?

**Comment by nbonacchi** [comment]
I'm confused, there are 2 problems here, maybe we should split the issues:

**Extractor issue**
I agree with you, it looks like the ephys_trials extractors are failing in these 3 cases:

_For the non mock session_
- in the first example (a no_go trial) the extractor seems to not be able to extract the stim freeze mainly because it does not exist, it also attributes weird names to events that are clearly of the next trial.
- in the second example (an error trial) it looks like the frame2ttl transition before the stim OFF event was skipped and the extractor does not check the stimfreeze trigger time to disambiguate these cases.

_For the mock session example_
- (error trial) It looks similar to the error trial in the next example but I'm not sure, did you check the previous and subsequent trials to see if there is a misalignment in terms of trial number? 

**task_qc visualization issue**
Regarding mock sessions use the ephys extractors and they should be extracted if ephys data is present, there is either no ephys data or there is a problem with the visualization that should call the ephys extractors for the qc. We can talk about this on Friday at our meeting and define what and how they are used. Also, there seems to be a confusion with terminology which we should clarify, between mock session as required by the physiology procedure and test sessions we ask users to perform sporadically to check the output or debug some specific issues.

**Comment by oliche** [comment]
As of now the stim freeze is the second to last frame2ttl event before the next trial start.

**Comment by GaelleChapuis** [comment]
I'm not sure stimFreeze_times can actually be accurately detected on the F2TTL trace (it might stay from Low-To-Low state).
@nbonacchi could you comment on this? If this is true, it might be worth using only stimFreezeTriggers_times for the QC as an approximation.

**Comment by GaelleChapuis** [comment]
For 193fe7a8-4eb5-4f3e-815a-0c45864ddd77 trial 616 there is no stimFreeze trigger it seems (at least none is plotted on the Task QC GUI), whilst there is a response on that trial.

From the task architecture, I however understand that there should always be a stimFreeze trigger if a response is registered.

This seems to be a bug @nbonacchi, could you confirm the logic here?

**Comment by nbonacchi** [comment]
It should be the second to lase as @oliche is saying. 
However, not all trials have a freeze command (no_go trials) and the stimulus freezing does not flip the sync square explicitlt, meaning that the latest flick of the sync square (if the movement sync was working properly) is the last detected movement of the stim. 
However2, the sync square update while moving has never really worked so it could be that the latest sync square flip happens way before the stim actually freezes.
I'd ignore stimFreeze times altogether and only use stimFreezeTrigger.times for correct and error trials. 
I don't think anyone ever asked for this dataset except us for control purposes, if it's not working we shouldn't use it for QC.

**Comment by GaelleChapuis** [comment]
Let's not change the extraction of stimFreeze ; TODO: 
1. figure whether stimFreezeTriggers_times is extracted properly, by analyzing trials data
2. see how prevalent is the failure of the stimulus freezing before the response, and what are the delays
3. check that Bpod wheel movement (X1 encoding) engenders screen and frame2ttl change ; ideally, plot wheel trace as seen by Bpod onto the task QC GUI
