### ISSUE TITLE
[Bug report] - trials.probabilityLeft has wrong value in biased blocks

### ISSUE THREAD

**Issue by SebastianBruijns** [int-brain-lab/iblenv#128]
Hi,
I'm using trials.probabilityLeft to access the current block identity, and my code crashed for session
'b4f47820-4255-4504-8e30-d67fe330c2ef'
(use "one.load('b4f47820-4255-4504-8e30-d67fe330c2ef', dataset_types='trials.probabilityLeft')[0]" to get the problematic array)

It's a very short session, and one of the values in there is 0.7, only 0.5, 0.8 and 0.2 should be possible. Do we know what went wrong?

**Comment by k1o0** [comment]
I don't think this is a bug: this session used the trainingChoiceWorld protocol which does not have biased blocks (you can see that most trials have a probability of 0.5.  This protocol uses a form of anti-biasing whereby if the subject turns the wheel in the wrong direction repeatedly, the probability of the next trail being on the same side increases.  This is done to discourage a strategy of quickly turning the wheel in one direction because the returns quickly diminish.  This anti-biasing is removed in biasedChoiceWorld and the probability set is fixed at {0.5, 0.2, 0.8}.  

Feel free to reopen if anything is unclear.
