### ISSUE TITLE
[Usage question] - How to know if a session is a dud programmatically using rest query

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#139]
**Describe the question you have**
What is the current way to catch a dud session currently (programmatically)? Checking if any task is marked as abandoned?
For example, there is no ephys data on the local server for this session:
```
{'subject': 'ibl_witten_17',
 'start_time': '2020-07-14T16:56:23.927610',
 'number': 1,
 'lab': 'wittenlab',
 'project': 'ibl_neuropixel_brainwide_01',
 'url': 'https://alyx.internationalbrainlab.org/sessions/a917f2f9-e7e2-4c61-9230-b0e751f1f13c',
 'task_protocol': '_iblrig_tasks_ephysChoiceWorld6.4.0'}
```
It could either be a dud session, or sign of a problem with the ephys rig to local server transfer.

**Comment by GaelleChapuis** [comment]
There are actually no tasks for this eid:
```
eid = 'a917f2f9-e7e2-4c61-9230-b0e751f1f13c'
tasks = one.alyx.rest('tasks', 'list', session=eid)
```

**Comment by k1o0** [comment]
What is you're goal?  If for example you want to count the number of sessions I would filter by sessions that contain particular data.  If you want to count empty sessions you could query for sessions without data....

**Comment by GaelleChapuis** [comment]
I would like to know whether the session is a dud session (a test session if you like, which data should not have been uploaded), versus a real session (for which datasets need to be complete)

**Comment by k1o0** [comment]
It seems to me that there wouldn't be any robust way to do this.  I assume that if the user follows protocol (do they select a dummy mouse?) it shouldn't be uploaded to Alyx.  If it is, then please re-open as an iblrig issue.  Otherwise if a user runs a test session under a real mouse name then it would be identical to a real session, albeit shorter.  If a user does this they should delete the session from Alyx and mark any tasks as abandoned. I think this is the only time when deleting session is warranted.
