### ISSUE TITLE
[Bug report] - erratic alignment behavior for ephys alignment gui, see latest comment, applies to session in original comment

### ISSUE THREAD

**Issue by cskrasniak** [int-brain-lab/iblenv#165]
Might be similar to Issue #164, but even though clusters data is available on the server, for this session I get an error saying it is absent when trying to perform the ephys alignment: 
```CSH_ZAD_019
probe01
2020-08-14
7f6b86f9-879a-4ea2-8531-294a221af5d0
2021-01-08 08:22:59.730 WARNING  [one.py:177] dataset _iblqc_ephysSpectralDensity.amps not found for session: 7f6b86f9-879a-4ea2-8531-294a221af5d0
cluster data was not found, some plots will not display
Traceback (most recent call last):
  File "ephys_atlas_gui.py", line 1100, in data_button_pressed
    self.scat_drift_data = self.plotdata.get_depth_data_scatter()
  File "/Users/ckrasnia/Desktop/Zador_Lab/IBL/int-brain-lab/iblapps/atlaselectrophysiology/plot_data.py", line 74, in get_depth_data_scatter
    amp_range = np.quantile(self.spikes['amps'][self.spike_idx], [0, 0.9])
AttributeError: 'PlotData' object has no attribute 'spike_idx'```

**Comment by cskrasniak** [comment]
update for this same session is that now as I try to do the alignment, I get the following strange behavior:
![image](https://user-images.githubusercontent.com/46825765/104188984-0832d800-53e8-11eb-9dc1-7f0fa01e6aaa.png)
The first alignment landmark I place works as intended
![image](https://user-images.githubusercontent.com/46825765/104189010-154fc700-53e8-11eb-85ad-aa2e18a054a7.png)
I then select another landmark, in this case at the top of CA1
![image](https://user-images.githubusercontent.com/46825765/104189068-2d274b00-53e8-11eb-826f-2c2d4f2ab543.png)
when I hit fit with a second landmark, it adjusts so that the most recent landmark is aligned, but it shifts the position of the previously placed landmark(s) here shifting the previously labelled vis layer 5 down
![image](https://user-images.githubusercontent.com/46825765/104189120-3ca69400-53e8-11eb-83ff-bb3be9c0aa26.png)
This behavior continues to get worse as I add more landmarks, with the previous ones no longer in their intended position, but the newest one is correct
![image](https://user-images.githubusercontent.com/46825765/104189659-f9005a00-53e8-11eb-908e-bc47f27e0e35.png)

**Comment by mayofaulkner** [comment]
Thanks for reporting this problem. I had a look into it and it was occurring because the shift required was so large, the user reference point was located beyond the extreme top reference point and so was causing weird behaviour in the interpolation. In the latest commit to develop https://github.com/int-brain-lab/ibllib/commit/39c610142c24a8942400dafbe0d8c84973b5ebbd I have extended the initialisation of the extreme reference points so this won't happen any more. If you pull the latest changes from ibllib develop you should be able to align as expected. I'll close this issue but feel free to reopen if you find you are still having problems!
