### ISSUE TITLE
[Bug report] - Missing histology tracing

### ISSUE THREAD

**Issue by SebastianBruijns** [int-brain-lab/iblenv#171]
The session with the eid '572a95d1-39ca-42e1-8424-5c9ffcb2df87', of mouse 'KS020' previously had Histology tracing available, but now when trying to download it with

`load_spike_sorting_with_channel(eid, one=one)`

I get

> 2021-01-20 16:31:49.346 WARNING  [one.py:143] Histology tracing for probe00 does not exist. No channels for probe00
2021-01-20 16:31:49.346 WARNING  [one.py:143] Histology tracing for probe01 does not exist. No channels for probe01

There was an issue with this session, where there was temporal drift in the neural responses, thus some aspects might have been in need of recomputing and in that process the histology got lost somewhere?

**Comment by oliche** [comment]
This was indeed a nasty bug of database sync (specific to UCL). Fixed in cortex-lab/alyx#1e6ca3c5185d9101ee2ee1eb420422f5ceb677c9

I've recovered the positions from previous database backups. Code here: int-brain-lab/ibldevtools#e330dce751e7bc01fc3982ed6c0cd751a64e2749

It proves we can recover stuff we clobbered. Let's try not to do this again...
