### ISSUE TITLE
[Usage question] - Ephys data extraction - what is the task to launch to get the _iblqc_ datasets

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#190]
**Describe the question you have**
Some insertions have raw ephys data on FI, but are missing those alf datasets :

```
dtypes_ephys = [
    '_iblqc_ephysTimeRmsLF.rms',
    '_iblqc_ephysTimeRmsLF.timestamps',
    '_iblqc_ephysSpectralDensityLF.power',
    '_iblqc_ephysSpectralDensityLF.freqs',
    '_iblqc_ephysTimeRmsAP.rms',
    '_iblqc_ephysTimeRmsAP.timestamps',
    '_iblqc_ephysSpectralDensityAP.power',
    '_iblqc_ephysSpectralDensityAP.freqs',
]
```

When are these datasets created?
What task should the user set to Waiting to make them generated?

**Comment by GaelleChapuis** [comment]
Example insertion ID: 11a5a93e-58a9-4ed0-995e-52279ec16b98

**Comment by mayofaulkner** [comment]
They are created as part of the rawephysqc task. There are some cases (I think mainly due to space issues) where the raw data was removed before these were extracted which means they were not computed. Setting the tasks to waiting won't solve this as the data is no longer on the servers. Probably another scenario where we should use the flatiron compute node.

**Comment by GaelleChapuis** [comment]
Thanks for the clear explanation! Would it help if I came up with a list of insertions where this happens and to prioritize ?
