### ISSUE TITLE
[Bug report] - HabituationTrials data and paths output mismatch

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/iblenv#221]
```python
from ibllib.io.extractors.habituation_trials import HabituationTrials

hab = HabituationTrials(session_path)

out_data, paths = hab.extract(save=True)

len(out_data)  # 15
len(paths)  # 11
```
The extractor returns a different set of extracted variables than the files that it saves.
Consider returning a dict with names for the arrays / only return what is being saved.

**Comment by k1o0** [comment]
What's the session?

**Comment by k1o0** [comment]
The problem appears to come from the normal trials extractor changing: https://github.com/int-brain-lab/ibllib/blob/61d2c4c945f5d1f42a963c87817e04c7c5bfe1e0/ibllib/io/extractors/habituation_trials.py#L41-L42

These two lines call the extractor classes from training_trials and biased_trials.  At one point they returned a dictionary with the keys that are now missing, namely `['contrastLeft', 'contrastRight', 'intervals', 'goCue_times']`
```
# Extract datasets common to trainingChoiceWorld
training = [ContrastLR, FeedbackTimes, Intervals, GoCueTimes, StimOnTriggerTimes]
out, _ = run_extractor_classes(training, session_path=self.session_path, save=False,
                                bpod_trials=self.bpod_trials, settings=self.settings)
```

Either those keys were renamed or removed (or the names are incorrect in the Habituation.var_names property).  While FlatIron is down I can't check because I don't have the local data so I'll let you investigate further.  Set a breakpoint there and check the keys in `out`.

**Comment by nbonacchi** [comment]
:shrug: as far as I know nothing changed in the training_trials or biased_trials extractor. I did not make this extractor and I can't easily fix it without understanding why you reused the training and biased extractors in the first place, the Habituation task is a completely different state machine implementation, so there is no guarantee that the biased or training trials extractors would work, is this in production? AFAIK none was looking at these data.

**Comment by k1o0** [comment]
It is in production.  I reused those extractors because the extraction of those datasets were identical (identical fields in the Bpod trials file).  You do not need to understand anything special to follow my above instructions (and after all you wrote all of these protocols).  Please add a breakpoint where I mentioned and report back what is in `out`, namely how the keys are different to `['contrastLeft', 'contrastRight', 'intervals', 'goCue_times']`.

**Comment by k1o0** [comment]
Another cause of this might be a change in the behaviour of the base class.  Not all extracted datasets are saved: https://github.com/int-brain-lab/ibllib/blob/61d2c4c945f5d1f42a963c87817e04c7c5bfe1e0/ibllib/io/extractors/habituation_trials.py#L21-L24

The exclude list also has a length of 4: 
`exclude = ['itiIn_times', 'stimOffTrigger_times', 'stimCenter_times', 'stimCenterTrigger_times']`

These variables are not saved so the corresponding values in `HabituationTrials.save_names` are None (we use some data for QC but don't register it to Alyx).  In the `_save` method of the base class None save names are ignored (not saved): https://github.com/int-brain-lab/ibllib/blob/61d2c4c945f5d1f42a963c87817e04c7c5bfe1e0/ibllib/io/extractors/base.py#L87-L88

The base class doesn't return the None file names, which is fine.  I'm not sure this is actually an issue: the length of var_names and save_names is equal in the class and the save method returns you the datasets that were actually saved.  If you want to save all of them, you can replace the None values with a dataset file name.  The save method needs a 1:1 map between the data and file names but the user doesn't.  If you run extract you can turn it into a dict like so:

```
hab = HabituationTrials(session_path)
out_data, paths = hab.extract(save=True)
data_dict = {k: v for k, v in zip(out, hab.var_names)}
```
This is precisely what `run_extractor_classes` does when it returns you a dict.

**Comment by k1o0** [comment]
Hopefully the above solution works for you.  Re-open if necessary.
