### ISSUE TITLE
[Bug report] - test_responsive_units fails on windows

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/iblenv#227]
FAILED tests\test_task.py::TestTask::test_responsive_units - AssertionError: ...
============ 1 failed, 71 passed, 1 skipped, 14 warnings in 45.64s ============

CI run [here](https://github.com/nbonacchi/ibllib/runs/2383867540?check_suite_focus=true)

The test was made by @guidomeijer maybe he'll hae insights

To our resident windows gurus @k1o0 @mayofaulkner: 

The test target is `brainbox.task.closed_loop.responsive_units()`, in the main scope of the func everything seems perfectly crossplatform and I stopped right before starting to look more in depth inside `scipy.stats.wilcoxon()` or `brainbox.task._statsmodels.multipletests()`. 
The idea is that these funcs might yield different significance results because of something like: if these functions use some random variable  and if the randomness is initialized differently from windows to linux the func might yield different significance values. 
But of course it might be something completely different. That was just my personal debugging rabbit hole :shrug:

**Comment by guidomeijer** [comment]
It looks like there were too few trials to calculate exact p-values so the test would give a different result every time it was run. I got this error (on a Windows laptop): Exact p-value calculation does not work if there are ties. Why this only happens on Windows and why suddenly now, I don't know. I duplicated the fake trial vector so that there are more trials and all tests are passing now. It's on a branch, I created a PR: https://github.com/int-brain-lab/ibllib/pull/306
