### ISSUE TITLE
[Bug report] - VideoCompress run before all files copied

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblenv#236]
**Describe the bug**
A common error for this task is missing data.  Tasks fail the data check, apparently because the task was started before all files were copied over to the local server.  

**To Reproduce**
An example [from cortexlab](https://alyx.internationalbrainlab.org/admin/jobs/task/2c83dcb0-5e90-4379-857a-b02f7ecd0ad2/change/) shows a task where there are no raw camera timestamps.

**Expected behavior**
The task should only be run when all the data have been copied over to the local server.  The required data are:
```
'_iblrig_Camera.frame_counter',
'_iblrig_Camera.GPIO',
'_iblrig_Camera.timestamps',
'_iblrig_taskData.raw',
'_iblrig_taskSettings.raw',
'_iblrig_Camera.raw',
--------- EPHYS ---------
'_spikeglx_sync.channels',
'_spikeglx_sync.polarities',
'_spikeglx_sync.times',
'ephysData.raw.meta',
'ephysData.raw.wiring'
```

**Comment by k1o0** [comment]
More examples:
https://alyx.internationalbrainlab.org/admin/jobs/task/96d96616-eeda-4623-82fa-5c5475fe0526/change/
https://alyx.internationalbrainlab.org/admin/jobs/task/8f224642-bf70-4df1-a62f-1add6f6767a3/change/

**Comment by nbonacchi** [comment]
Make sure ibllib/iblscripts are up to date, this issue was explicitly fixed a while ago. The pipeline triggering event is the existence of a `raw_session.flag`, nothing else should give the OK to start preprocessing. the only way to have this flag from an ephys session is if all the transfers (from behavior, video, and ephys PCs) have completed successfully ([here](https://github.com/int-brain-lab/ibllib/blob/97a5502648d55dd9471b171c298d9a3b1ca6b43e/ibllib/pipes/misc.py#L379)).

**Comment by k1o0** [comment]
I'm going to go ahead and close this for now.  Hopefully the issue is resolved.
