### ISSUE TITLE
How to save wheel data with water reward times? 

### ISSUE THREAD

**Issue by rkim48** [int-brain-lab/iblenv#241]
I am currently using the rig with some tweaking of the code for a simple "turn past threshold to get water reward" task. I can use the rotary encoder module to see the wheel movement in real time and save it to a text file which has been convenient for me. 
However, I would like to additionally save reward timestamps or threshold crossings so I can analyze the wheel data right before reward to better set my wheel thresholds for following sessions. 

Is there an easy way of doing this with the rotary encoder module in the GUI? I tried checking the enable events box for the rotary encoder module window but that didn't give me the reward/threshold crossing timestamps. If I look at the text file all I see are P data types which are the wheel angle data. I would like to include the data type E timestamps which reading from the rotary encoder module_api.py file seems like would tell me when these threshold crossings occur. 

I attached an example output file from the rotary encoder module. 

[b4_5_29.txt](https://github.com/int-brain-lab/iblenv/files/6565455/b4_5_29.txt)

**Comment by nbonacchi** [comment]
@rkim48 the file you shared is the output from a data stream from the RE to pybpod. There is a unit missing that is quite important i.e. the RE timestamp, the PC time is the time when python processed the data and not when it was acquired. Depending on the precision you require this might be problematic, the PC time might fluctuate because of serial buffers, PC interrupts or scheduling priorities. The RE timestamps need to be aligned to the main Bpod clock but are more accurate.

In the standard task use Bonsai to process and save the position and event streams from the RE. The Bonsai workflow for the stimulus should have a RotaryEncoder node that splits into 2 one stream is for the (P)positions and another is for the (E)vents.
The 'P' stream is automatic every time the RE detects a position change/reset of the position
The 'E' stream is user defined, i.e., one has to build a message and then send that message through the RE to Bonsai.
This is how we avoid using software triggeres that are much slower to execute. The code sent from pybpo to the Bonsai workflow is based on ints and pretty simple: 1 = Hide the stimulus, 2 = Show the stimulus, 3 = close the loop, 4= Freeze the stimulus and in the current release candidate 5 = show the stimulus at the center. 

The thresholds you are talking about are RE thresholds one sets at the beginning of the session. the RE module has the ability of receiving 8 thresholds that will trigger once whenever the position passes through their value. This trigger is "seen" by Bpod and can be used to change the state. In fact in the standard IBL task we use 4 thresholds 2 for detecting "movement" during quiescence and 2 for detecting 35 deg of movement.  

To solve your particular issue it seems to me that you are not looking into the Bpod behavior data that is returned at every trial. the Bpod data has the Bpod_timestamps for all of the state machine events, the water delivery is one of them.
