### ISSUE TITLE
[Usage question] - Frame 2TTL Connection Error 

### ISSUE THREAD

**Issue by srhaiken** [int-brain-lab/iblenv#263]
I am constantly getting the attached error, and no matter how I troubleshoot, I am unable to succeed in fixing the error. Any thoughts or suggestions? I have tried a new IBL Frame 2TTL piece (worked for another rig, won't work for this one), I have used different usb cords, I have taken down and re-built the entire box, and I have restored this computer with a clone of a computer that houses a working rig. Thank you! 
<img width="969" alt="Screen Shot 2021-09-27 at 12 57 41 PM" src="https://user-images.githubusercontent.com/86740288/134953103-7ed24921-44da-4bc1-b566-801239d1e84e.png">

**Comment by k1o0** [comment]
Hi, 

If you haven't already, try a different USB port, preferably one at the back of the computer.  Next double-check that the frame2ttl is plugged into BNC1 of the Bpod board.  After plugging it into a new USB port, repeat these steps from the install instructions:
- Install USBTree viewer (UsbTreeView.exe)
- Open USBTree viewer and disconnect and connect the USB cable of the Frame2TTL to find out which COM port belongs to it, note this down
- Make sure the COM port is correctly set in `iblrig_params\.iblrig_params.json`

Also double-check the USB latency settings:
- In Power settings, choose ‘performance optimized’ so that the PC never goes to sleep. The display can go to sleep after 1 hour of inactivity.
- Set the USB communication latency to 1ms (explanatory article here).
- Find the USB driver under Device Manager (Ports (COM & LTP)
- Right click on USB Serial Port (COM) and select Properties
- Go to Port Settings, click on Advanced and change the Latency Time (ms) to 1
- Click OK 

After all this, run `bpod_ttl_test` and cross your fingers!

**Comment by srhaiken** [comment]
That removed the connection error - thank you so much! However, now when the task is running, no stimulus appears on the screen. I have already un-downloaded and re-downloaded bonsai. Do you have any further suggestions? Thank you so much!

**Comment by srhaiken** [comment]
For more information: The error I am receiving from bonsai says, "All attempts to open capture devices returned IntPtr.Zero. See debug log for verbose list.

**Comment by k1o0** [comment]
That sounds to me like it may be a camera issue.  Perhaps try re-seating the camera cables and double-checking that everything is wired correctly.  @nbonacchi any other ideas?

**Comment by srhaiken** [comment]
After doing that, the error now reads "The type initializer for 'OpenCV.Net.Native.NativeMethods' threw an exception."

**Comment by srhaiken** [comment]
Which is an error I frequently get on the working rig I use, but for this new rig it doesn't matter, the stimulus is still not showing up on the screen

**Comment by nbonacchi** [comment]
Is the error from the stimulus workflow or the camera workflow? I get the IntPtr0 whenever a com port is misconfigured usually the microphone in my case.

For the open CV error try deleting the Bonsai folder running `git reset --hard` command from the command line, then navigate to the Bonsai folder that should have reappears and double click on Bonsai64.exe
This will reinstall the rig bonsai.
Make sure the installation does not error. 

You can always just open bonsai and check out if the visual stimulus or the camera/mic workflows are running correctly by opening the rig bonsai (c:\iblrig\Bonsai\Bonsai64.exe) and opening the workflow you want to check.

**Comment by k1o0** [comment]
No response in almost a month, closing for now.

**Comment by srhaiken** [comment]
Both the visual stimulus and the camera/mic workflows are running correctly, and yet we are still getting this error
