### ISSUE TITLE
[Bug report] - cannot connect to ONE

### ISSUE THREAD

**Issue by naureeng** [int-brain-lab/iblenv#282]
**Describe the bug**
We had an issue recently in the Gatsby Unit where the disk space was 100% full. I cleared my ONE cache files and data downloads at that time and cannot connect to ONE. 
![Screenshot from 2022-01-26 15-34-29](https://user-images.githubusercontent.com/32179063/151194501-8d43faf6-9f03-43d1-8db3-d9c2e0acbc90.png)

**Comment by mayofaulkner** [comment]
Hi, could you see if you can find a file called .one_params (should be in the user home folder) and delete this file. Could you then setup one again using the following
```
from one.api import ONE
one = ONE(base_url='https://alyx.internationalbrainlab.org')
```
It should prompt you for your alyx user credentials

**Comment by naureeng** [comment]
I keep being signed in as not myself:

One (online, https://alyx.internationalbrainlab.org)

**Comment by k1o0** [comment]
Run 
```
from one.api import OneAlyx
new_one = OneAlyx.setup(base_url='https://alyx.internationalbrainlab.org', make_default=True)
```

You will need to input the setting again.

**Comment by naureeng** [comment]
I do not have a .one_params file. It creates a folder called one and inside that folder is a file called 
.alyx.internationalbrainlab.org
![Screenshot from 2022-02-03 18-45-38](https://user-images.githubusercontent.com/32179063/152408758-5cde2e21-cc85-4ca4-b7f3-03fe2ba52edb.png)

**Comment by mayofaulkner** [comment]
Hi, Nicco deleted the message, but please could you make sure that you don't share any files that have any passwords on them publicly. If in doubt send one of us a PM on slack! Thanks

**Comment by naureeng** [comment]
oh sorry about that all! in any case, do you have ideas on how to proceed? I'm going to try installing everything from scratch today

**Comment by mayofaulkner** [comment]
When you install everything from scratch. Make sure to run this command first 
```
from one.api import ONE
one = ONE(base_url='https://alyx.internationalbrainlab.org')
```
It will then prompt you for all your credentials

**Comment by naureeng** [comment]
I'm really confused (I followed all the steps above). I don't get a .one_params file created as before. I get a folder built called .one and within that is something similar to the params file called .alyx.internationalbrianlab.org 

And it still says:
One (online, https://alyx.internationalbrainlab.org)

**Comment by k1o0** [comment]
Hi Naureen, it should say that: it means you are connected to the main database.  Also the `.one_params` file was removed from ONE many months ago.  Can you please clarify whether you still have a problem using ONE?  If you followed Mayo's suggestion and entered the correct credentials you should be able to query the main database (i.e. https://alyx.internationalbrainlab.org/).

**Comment by naureeng** [comment]
That is very unclear and misleading. I even wrote a message 12 days ago stating: 

I keep being signed in as not myself:

One (online, https://alyx.internationalbrainlab.org/)

It should have been made clear that is the response expected... 12 days ago. I was told that .one_params was removed many months ago for the first time today... I cannot find a single message on the IBL Slack explicitly stating that this occurred and there are recent messages discussing the .one_params file. 

I will close the issue but I really feel these two vital pieces of information: (1) there is no longer a .one_params file and (2) the new response expected for one=ONE() is One (online, https://alyx.internationalbrainlab.org/), should have been included. In any case, fingers-crossed it's all good-to-go and thank you for your time always.

**Comment by k1o0** [comment]
I'm sorry, I don't quite understand.  Please could you explain precisely what you found misleading about the object string representation (i.e. `One (online, https://alyx.internationalbrainlab.org/)`)? 'One' is the name of the API object class, 'online' means that you are in remote mode (in other words connected to a remote database), and 'https://alyx.internationalbrainlab.org/' is the URL of the database.  

The change to the object's string representation and the parameters file were made over 8 months ago.  We notified users on Slack of major changes to ONE (we called it ONE2 at the time).

The parameters file is not meant to be directly used, that's why it is a hidden file on linux (files that start with a period are hidden) and why it's in user data on Windows (as opposed to, say, My Documents).  The parameters file may change at any time without notice.  We expect users to use the safer `setup` method to change their parameters.  Information on setting up parameters can be found here: https://int-brain-lab.github.io/ONE/one_installation.html

If you want to see what user you're connected as: `print(one.alyx.user)`.

**Comment by naureeng** [comment]
When I do as you've suggsted: 

print(one.alyx.user)
None

It's not coming up as my username.

**Comment by k1o0** [comment]
No feedback from user for almost a month, closing issue for now
