### ISSUE TITLE
Why is Conda environment building no longer supported?

### ISSUE THREAD

**Issue by berkgercek** [int-brain-lab/iblenv#320]
It seems odd to me that the ability to build an environment at all using conda or mamba is completely removed from this repo. While I understand wanting to change the instructions to a pip-only set in order to simplify the workload of support on the staff, completely deleting the yaml file was a misstep in my opinion.

I don't see any harm in keeping the files there for those who know how to use them. I certainly would like them back! Mamba massively simplifies my workflow, especially when regularly upgrading/downgrading packages.

**Comment by micheleangelofabbri** [comment]
Interestingly mamba just had it's v1.0.0 release today. Prior to that, it was in beta. We ran into numerous build issues with mamba whenever conda made changes that the mamba folks did not account for. Perhaps that will no longer be a problem, but for now it is still not something that I personally feel comfortable instructing all users of iblenv to work with. 

The yaml file and conda build instructions were not taking into account some of the delicate nuances when working with conda and pip package management in conjunction. This was causing a multitude of inconsistencies when individuals were attempting to build iblenv on different systems. That file also included many unused packages and packages that were in a pre-release state. This was not simply an effort to ease the workload of supporting different build options, it was an effort to create a consistent build option.

If you are regularly upgrading and downgrading packages, I would urge you to read this article - https://www.anaconda.com/blog/using-pip-in-a-conda-environment

Feel free to reach out to me over slack or otherwise if this is unsatisfactory for your use case.
