### ISSUE TITLE
Extract new datasets: stim on trigger and quiescence period

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/iblenv#331]
## Extract new datasets for Charline and Naureen working on behaviour models

- [x] Julia: on the subject trial tables, add quiescence period and stim on trigger from jsonable files
- [x] OW: trials extractors: extract quiescence period to new dataset and create dataset type on Alyx released in 2.23.0
- [ ] Julia: extract the datasets for all sessions relevant 

## StimOn trigger analysis
- [ ] quantifiy number of  BWM sessions count stimOn > stimTrigger
- [ ] quantify stimOn - StimTrigger per rig
- [ ] update extractor to set stim-on + delay ?

**Comment by juhuntenburg** [comment]
Julia

- [ ] Check that all existing subjectTrials tables now indeed have quiescence for all trials
- [ ] Change the subjectTrials script to use the quiescencePeriod dataset (instead of or over computing it)
- [ ] Check for sessions that don't have the quiescence Period dataset and compute if possible
