### ISSUE TITLE
[Bug report] - Loading dataset in Histology alignment GUI

### ISSUE THREAD

**Issue by GaelleChapuis** [int-brain-lab/iblenv#41]
**Describe the bug**
Users could not load data from KS023, 2020-12-10, probe00

**To Reproduce**
Load data from KS023 data does not appear, or when it appears, GUI crashed.

**Comment by mayofaulkner** [comment]
Between ~3- 4:30 pm on 14/09/20 `one.load` with cortexlab data wasn't working
```
data_path  = one.load(eid, dataset_types='clusters.rawInd')
```
returned `None`

Now it seems to be working and downloads data correctly.  

Will close the issue now but will reopen if problem returns

**Comment by oliche** [comment]
Maintenance going on on Alyx caused those datasets to have an exist flag set to False for ~45 minutes, which prevents the data from being downloaded.
Normally the disk cached version should have been used, but since there was a hash mismatch, the program attempted to re-download the file and caused the failure.
