### ISSUE TITLE
[Bug report] 3 Errors when loading repeated site data

### ISSUE THREAD

**Issue by SebastianBruijns** [int-brain-lab/iblenv#78]
Some of these 3 may already have been reported, but I'm not quite sure, so I'll list them all.
These are caused by calling
> load_spike_sorting_with_channel(eid, one=one)
with some eids.

1. These 3 and others:

['a66f1593-dafd-4982-9b66-f9554b6c86b5', 'ee40aece-cffd-4edb-a4b6-155f158c666a', 'ebe090af-5922-4fcd-8fc6-17b8ba7bad6d']

cause:

>   File "lab_region_plot.py", line 45, in <module>
    spk, clus, chn = load_spike_sorting_with_channel(eid, one=one)
  File "/home/sebastian/iblenv/ibllib-repo/brainbox/io/one.py", line 223, in load_spike_sorting_with_channel
    dic_spk_bunch, dic_clus = load_spike_sorting(eid, one=one)
  File "/home/sebastian/iblenv/ibllib-repo/brainbox/io/one.py", line 149, in load_spike_sorting
    return _load_spike_sorting_local(session_path)
  File "/home/sebastian/iblenv/ibllib-repo/brainbox/io/one.py", line 155, in _load_spike_sorting_local
    probes = alf.io.load_object(session_path.joinpath('alf'), 'probes')
  File "/home/sebastian/iblenv/ibllib-repo/alf/io.py", line 271, in load_object
    files_alf, parts = _ls(alfpath, object, **kwargs)
  File "/home/sebastian/iblenv/ibllib-repo/alf/io.py", line 207, in _ls
    object = files.alf_parts(alfpath.name)[1]
  File "/home/sebastian/iblenv/ibllib-repo/alf/files.py", line 97, in alf_parts
    raise ValueError('Invalid ALF filename')
ValueError: Invalid ALF filename

2. 'dda5fc59-f09a-4256-9fb5-66c67667a466' causes this and returns nothing:

>  Channels in probe probe00 does not have the right element number compared to cluster. Data in new cluster key acronym is thus returned empty.
Channels in probe probe00 does not have the right element number compared to cluster. Data in new cluster key atlas_id is thus returned empty.
Channels in probe probe01 does not have the right element number compared to cluster. Data in new cluster key acronym is thus returned empty.
Channels in probe probe01 does not have the right element number compared to cluster. Data in new cluster key atlas_id is thus returned empty.
Channels in probe probe00 does not have the right element number compared to cluster. Data in new cluster key acronym is thus returned empty.
Channels in probe probe00 does not have the right element number compared to cluster. Data in new cluster key atlas_id is thus returned empty.
Channels in probe probe01 does not have the right element number compared to cluster. Data in new cluster key acronym is thus returned empty.
Channels in probe probe01 does not have the right element number compared to cluster. Data in new cluster key atlas_id is thus returned empty.

3. These 4:

['dda5fc59-f09a-4256-9fb5-66c67667a466', '03cf52f6-fba6-4743-a42e-dd1ac3072343', 'f312aaec-3b6f-44b3-86b4-3a0c119c0438', '7f6b86f9-879a-4ea2-8531-294a221af5d0']

cause:

> Traceback (most recent call last):
  File "lab_region_plot.py", line 45, in <module>
    spk, clus, chn = load_spike_sorting_with_channel(eid, one=one)
  File "/home/sebastian/iblenv/ibllib-repo/brainbox/io/one.py", line 227, in load_spike_sorting_with_channel
    dic_clus = merge_clusters_channels(dic_clus, channels, keys_to_add_extra=None)
  File "/home/sebastian/iblenv/ibllib-repo/brainbox/io/one.py", line 196, in merge_clusters_channels
    clu_ch = dic_clus[probe_labels[i_p]]['channels']
KeyError: 'Probe00'

**Comment by mayofaulkner** [comment]
Hey Sebastian, thanks for posting these errors. So i've looked into them and all of the errors are coming from missing data at some point during the pipeline. 

1. This error arises because the alf folder for the individual probes haven't been extracted and the spikes and clusters datasets aren't yet on the server. I will take a look into these sessions to see why they are missing.

2. and 3. These errors are happening because the histology tracing hasn't yet been conducted in these subjects and so the locations of the channels is still unknown. We need to chase down the experimenters and ask them to trace these as a priority so we can get this data.

This sheet gives an overview of where all the status of the repeated site data, (I think it is a bit outdated now as you have some new eids that aren't listed there.)
https://docs.google.com/spreadsheets/d/1w6a8IAYSvP41pv_kqH_MTk8k9cymLKYdO0F3gkN3M3Y/edit#gid=0

I'll close this issue for now but feel free to reopen it if you run into other problems.

**Comment by SebastianBruijns** [comment]
Thanks Mayo, that's super helpful. If the code goes wrong because of missing data, should we add this information to the error message, so that people know what caused the problem (not a bug), and they also get an idea who to bother to solve the problem?

**Comment by mayofaulkner** [comment]
Yep, great suggestion! I'll adapt the code a bit so it gives more intuitive  error messages.
